service: serverless-aws-nodejs-ts
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action: 'dynamodb:*'
          Resource: arn:aws:dynamodb:us-east-1:471112938813:table/appointmentTable4
        - Effect: Allow
          Action: 'sns:Publish' # Permiso para publicar en SNS
          Resource: arn:aws:sns:us-east-1:471112938813:MySNSTopic
  environment:
    SNS_TOPIC_ARN:
      Ref: SnsTopic

plugins:
  - serverless-plugin-typescript

functions:
  getAppointment:
    handler: src/functions/getAppointment/handler.handler
    events:
      - httpApi:
          path: /appointment
          method: get
  addAppointment:
    handler: src/functions/addAppointment/handler.handler
    events:
      - httpApi:
          path: /appointment
          method: post

resources:
  Resources:
    appointmentTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: appointmentTable4
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    SnsTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: MySNSTopic
