service: serverless-aws-nodejs-ts
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

plugins:
  - serverless-plugin-typescript

functions:
  obtenerCita:
    handler: src/functions/obtenerCita/handler.handler
    events:
      - httpApi:
          path: /cita
          method: get
  agregarCita:
    handler: src/functions/agregarCita/handler.handler
    events:
      - httpApi:
          path: /cita
          method: post

resources:
  Resources:
    appointmentTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: appointmentTable3
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
